name: leyendo otro pipeline

on:
  push:
    branches:
      - main
jobs:
  call_workflow:
    name: nodepipeline
    uses: dlaverdep15/laboratorio-workflow2/.github/workflows/pipeline.yml@main
        



